spring.application.name=jdbc-basics

spring.datasource.url=jdbc:postgresql://localhost:5432/School
spring.datasource.username=postgres
spring.datasource.password=amit@1661
spring.datasource.driver-class-name=org.postgresql.Driver